"""add ondelete cascade to topics

Revision ID: 02dc3f7cd960
Revises: 5bec80fe0b5d
Create Date: 2026-01-29 11:58:26.575266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02dc3f7cd960'
down_revision: Union[str, Sequence[str], None] = '5bec80fe0b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('topics_chapter_id_fkey', 'topics', type_='foreignkey')
    op.create_foreign_key(
        'topics_chapter_id_fkey',
        'topics',
        'chapters',
        ['chapter_id'],
        ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('topics_chapter_id_fkey', 'topics', type_='foreignkey')
    op.create_foreign_key(
        'topics_chapter_id_fkey',
        'topics',
        'chapters',
        ['chapter_id'],
        ['id'],
    )
    # ### end Alembic commands ###
