"""add_comp_chat_sessions

Revision ID: 3852c215bdf6
Revises: h1i2j3k4l5m6
Create Date: 2026-06-25 22:36:50.119115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3852c215bdf6'
down_revision: Union[str, Sequence[str], None] = 'h1i2j3k4l5m6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comp_chat_sessions',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comp_subject_id', sa.Integer(), nullable=False),
    sa.Column('comp_chapter_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), server_default='', nullable=False),
    sa.Column('thread_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['comp_chapter_id'], ['comp_chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['comp_subject_id'], ['comp_subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_chat_sessions_thread_id'), 'comp_chat_sessions', ['thread_id'], unique=True)
    op.create_index(op.f('ix_comp_chat_sessions_user_id'), 'comp_chat_sessions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_comp_play_sessions_activity_group_id'), table_name='comp_activity_play_sessions')
    op.create_index(op.f('ix_comp_activity_play_sessions_activity_group_id'), 'comp_activity_play_sessions', ['activity_group_id'], unique=False)
    op.alter_column('user_comp_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_comp_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('user_comp_profiles_user_id_key'), 'user_comp_profiles', type_='unique')
    op.drop_index(op.f('ix_user_comp_profiles_user_id'), table_name='user_comp_profiles')
    op.create_index(op.f('ix_user_comp_profiles_user_id'), 'user_comp_profiles', ['user_id'], unique=True)
    op.drop_index(op.f('ix_user_notifications_user_is_read'), table_name='user_notifications')
    op.drop_constraint(op.f('user_streaks_user_id_key'), 'user_streaks', type_='unique')
    op.drop_index(op.f('ix_user_streaks_user_id'), table_name='user_streaks')
    op.create_index(op.f('ix_user_streaks_user_id'), 'user_streaks', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_streaks_user_id'), table_name='user_streaks')
    op.create_index(op.f('ix_user_streaks_user_id'), 'user_streaks', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('user_streaks_user_id_key'), 'user_streaks', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_notifications_user_is_read'), 'user_notifications', ['user_id', 'is_read'], unique=False)
    op.drop_index(op.f('ix_user_comp_profiles_user_id'), table_name='user_comp_profiles')
    op.create_index(op.f('ix_user_comp_profiles_user_id'), 'user_comp_profiles', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('user_comp_profiles_user_id_key'), 'user_comp_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_comp_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_comp_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_comp_activity_play_sessions_activity_group_id'), table_name='comp_activity_play_sessions')
    op.create_index(op.f('ix_comp_play_sessions_activity_group_id'), 'comp_activity_play_sessions', ['activity_group_id'], unique=False)
    op.drop_index(op.f('ix_comp_chat_sessions_user_id'), table_name='comp_chat_sessions')
    op.drop_index(op.f('ix_comp_chat_sessions_thread_id'), table_name='comp_chat_sessions')
    op.drop_table('comp_chat_sessions')
    # ### end Alembic commands ###
