"""add llm_notes and qa_patterns tables

Revision ID: 41771834264e
Revises: e670eb1a1a8a
Create Date: 2025-12-01 22:40:54.248343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41771834264e'
down_revision: Union[str, Sequence[str], None] = 'e670eb1a1a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_patterns',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Add new columns as nullable first
    op.add_column('llm_notes', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('llm_notes', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('llm_notes', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))

    # Migrate existing data: copy 'note' to 'content' and set title to 'Untitled'
    op.execute("UPDATE llm_notes SET title = 'Untitled', content = note WHERE title IS NULL")

    # Now make columns non-nullable
    op.alter_column('llm_notes', 'title', nullable=False)
    op.alter_column('llm_notes', 'content', nullable=False)

    op.create_foreign_key(None, 'llm_notes', 'chapters', ['chapter_id'], ['id'])
    op.drop_column('llm_notes', 'note')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_notes', sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'llm_notes', type_='foreignkey')
    op.drop_column('llm_notes', 'tags')
    op.drop_column('llm_notes', 'content')
    op.drop_column('llm_notes', 'title')
    op.drop_table('qa_patterns')
    # ### end Alembic commands ###
