"""Add ai_feedback to activity_answers

Revision ID: 5bec80fe0b5d
Revises: 9852db85a28a
Create Date: 2026-01-26 12:26:57.774118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5bec80fe0b5d'
down_revision: Union[str, Sequence[str], None] = '9852db85a28a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_answers', sa.Column('ai_feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint(op.f('activity_groups_chapter_id_fkey'), 'activity_groups', type_='foreignkey')
    op.create_foreign_key(None, 'activity_groups', 'chapters', ['chapter_id'], ['id'])
    op.alter_column('activity_play_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('fk_chapter_activities_activity_group_id'), 'chapter_activities', type_='foreignkey')
    op.create_foreign_key(None, 'chapter_activities', 'activity_groups', ['activity_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapter_activities', type_='foreignkey')
    op.create_foreign_key(op.f('fk_chapter_activities_activity_group_id'), 'chapter_activities', 'activity_groups', ['activity_group_id'], ['id'], ondelete='CASCADE')
    op.alter_column('activity_play_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'activity_groups', type_='foreignkey')
    op.create_foreign_key(op.f('activity_groups_chapter_id_fkey'), 'activity_groups', 'chapters', ['chapter_id'], ['id'], ondelete='CASCADE')
    op.drop_column('activity_answers', 'ai_feedback')
    # ### end Alembic commands ###
