"""update llm_notes and qa_patterns to pdf based

Revision ID: 8f4da26ad4f0
Revises: 41771834264e
Create Date: 2025-12-01 22:46:23.635427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f4da26ad4f0'
down_revision: Union[str, Sequence[str], None] = '41771834264e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # LLM Notes: change from text content to PDF-based
    op.add_column('llm_notes', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('llm_notes', sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # Migrate existing data if needed
    op.execute("UPDATE llm_notes SET file_url = '' WHERE file_url IS NULL")
    op.alter_column('llm_notes', 'file_url', nullable=False)

    op.drop_column('llm_notes', 'tags')
    op.drop_column('llm_notes', 'content')

    # QA Patterns: change from Q&A text to PDF-based
    op.add_column('qa_patterns', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('qa_patterns', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('qa_patterns', sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # Migrate existing data if needed
    op.execute("UPDATE qa_patterns SET title = question, file_url = '' WHERE title IS NULL")
    op.alter_column('qa_patterns', 'title', nullable=False)
    op.alter_column('qa_patterns', 'file_url', nullable=False)

    op.drop_column('qa_patterns', 'answer')
    op.drop_column('qa_patterns', 'tags')
    op.drop_column('qa_patterns', 'question')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_patterns', sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('qa_patterns', sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('qa_patterns', sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('qa_patterns', 'file_url')
    op.drop_column('qa_patterns', 'description')
    op.drop_column('qa_patterns', 'title')
    op.add_column('llm_notes', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('llm_notes', sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('llm_notes', 'file_url')
    op.drop_column('llm_notes', 'description')
    # ### end Alembic commands ###
