"""add competitive exam tables

Revision ID: a570eb3d3480
Revises: d4e5f6a7b8c9
Create Date: 2026-03-15 13:44:19.169676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a570eb3d3480'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_categories',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_categories_name'), 'exam_categories', ['name'], unique=True)
    op.create_table('exams',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exam_category_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_category_id'], ['exam_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_exam_category_id'), 'exams', ['exam_category_id'], unique=False)
    op.create_table('comp_exam_mediums',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_exam_mediums_exam_id'), 'comp_exam_mediums', ['exam_id'], unique=False)
    op.create_table('comp_levels',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('medium_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medium_id'], ['comp_exam_mediums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_levels_medium_id'), 'comp_levels', ['medium_id'], unique=False)
    op.create_table('comp_previous_year_papers',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('num_pages', sa.Integer(), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['comp_levels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_previous_year_papers_level_id'), 'comp_previous_year_papers', ['level_id'], unique=False)
    op.create_table('comp_subjects',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['comp_levels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_subjects_level_id'), 'comp_subjects', ['level_id'], unique=False)
    op.create_table('mock_tests',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['comp_levels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_tests_level_id'), 'mock_tests', ['level_id'], unique=False)
    op.create_table('comp_chapters',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('icon_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('include_subchapters', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['comp_subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_chapters_subject_id'), 'comp_chapters', ['subject_id'], unique=False)
    op.create_table('mock_test_questions',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('mock_test_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('options', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('correct_option_index', sa.Integer(), nullable=True),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mock_test_id'], ['mock_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_test_questions_mock_test_id'), 'mock_test_questions', ['mock_test_id'], unique=False)
    op.create_table('comp_sub_chapters',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['comp_chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_sub_chapters_chapter_id'), 'comp_sub_chapters', ['chapter_id'], unique=False)
    op.create_table('comp_activity_groups',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('comp_chapter_id', sa.Integer(), nullable=True),
    sa.Column('sub_chapter_id', sa.Integer(), nullable=True),
    sa.Column('timer_seconds', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comp_chapter_id'], ['comp_chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_chapter_id'], ['comp_sub_chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_activity_groups_comp_chapter_id'), 'comp_activity_groups', ['comp_chapter_id'], unique=False)
    op.create_index(op.f('ix_comp_activity_groups_sub_chapter_id'), 'comp_activity_groups', ['sub_chapter_id'], unique=False)
    op.create_table('comp_additional_notes',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('comp_chapter_id', sa.Integer(), nullable=True),
    sa.Column('sub_chapter_id', sa.Integer(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comp_chapter_id'], ['comp_chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_chapter_id'], ['comp_sub_chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_additional_notes_comp_chapter_id'), 'comp_additional_notes', ['comp_chapter_id'], unique=False)
    op.create_index(op.f('ix_comp_additional_notes_sub_chapter_id'), 'comp_additional_notes', ['sub_chapter_id'], unique=False)
    op.create_table('comp_chapter_artifacts',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('comp_chapter_id', sa.Integer(), nullable=True),
    sa.Column('sub_chapter_id', sa.Integer(), nullable=True),
    sa.Column('artifact_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comp_chapter_id'], ['comp_chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_chapter_id'], ['comp_sub_chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_chapter_artifacts_artifact_type'), 'comp_chapter_artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_comp_chapter_artifacts_comp_chapter_id'), 'comp_chapter_artifacts', ['comp_chapter_id'], unique=False)
    op.create_index(op.f('ix_comp_chapter_artifacts_sub_chapter_id'), 'comp_chapter_artifacts', ['sub_chapter_id'], unique=False)
    op.create_table('comp_llm_images',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('comp_chapter_id', sa.Integer(), nullable=True),
    sa.Column('sub_chapter_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comp_chapter_id'], ['comp_chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_chapter_id'], ['comp_sub_chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_llm_images_comp_chapter_id'), 'comp_llm_images', ['comp_chapter_id'], unique=False)
    op.create_index(op.f('ix_comp_llm_images_sub_chapter_id'), 'comp_llm_images', ['sub_chapter_id'], unique=False)
    op.create_table('comp_llm_notes',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('comp_chapter_id', sa.Integer(), nullable=True),
    sa.Column('sub_chapter_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comp_chapter_id'], ['comp_chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_chapter_id'], ['comp_sub_chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_llm_notes_comp_chapter_id'), 'comp_llm_notes', ['comp_chapter_id'], unique=False)
    op.create_index(op.f('ix_comp_llm_notes_sub_chapter_id'), 'comp_llm_notes', ['sub_chapter_id'], unique=False)
    op.create_table('comp_llm_textbooks',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('comp_chapter_id', sa.Integer(), nullable=True),
    sa.Column('sub_chapter_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comp_chapter_id'], ['comp_chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_chapter_id'], ['comp_sub_chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_llm_textbooks_comp_chapter_id'), 'comp_llm_textbooks', ['comp_chapter_id'], unique=False)
    op.create_index(op.f('ix_comp_llm_textbooks_sub_chapter_id'), 'comp_llm_textbooks', ['sub_chapter_id'], unique=False)
    op.create_table('comp_qa_patterns',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('comp_chapter_id', sa.Integer(), nullable=True),
    sa.Column('sub_chapter_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comp_chapter_id'], ['comp_chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_chapter_id'], ['comp_sub_chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_qa_patterns_comp_chapter_id'), 'comp_qa_patterns', ['comp_chapter_id'], unique=False)
    op.create_index(op.f('ix_comp_qa_patterns_sub_chapter_id'), 'comp_qa_patterns', ['sub_chapter_id'], unique=False)
    op.create_table('comp_student_notes',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('comp_chapter_id', sa.Integer(), nullable=True),
    sa.Column('sub_chapter_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audio_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comp_chapter_id'], ['comp_chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_chapter_id'], ['comp_sub_chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_student_notes_comp_chapter_id'), 'comp_student_notes', ['comp_chapter_id'], unique=False)
    op.create_index(op.f('ix_comp_student_notes_sub_chapter_id'), 'comp_student_notes', ['sub_chapter_id'], unique=False)
    op.create_table('comp_student_textbooks',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('comp_chapter_id', sa.Integer(), nullable=True),
    sa.Column('sub_chapter_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audio_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comp_chapter_id'], ['comp_chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_chapter_id'], ['comp_sub_chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_student_textbooks_comp_chapter_id'), 'comp_student_textbooks', ['comp_chapter_id'], unique=False)
    op.create_index(op.f('ix_comp_student_textbooks_sub_chapter_id'), 'comp_student_textbooks', ['sub_chapter_id'], unique=False)
    op.create_table('comp_student_videos',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('comp_chapter_id', sa.Integer(), nullable=True),
    sa.Column('sub_chapter_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comp_chapter_id'], ['comp_chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_chapter_id'], ['comp_sub_chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_student_videos_comp_chapter_id'), 'comp_student_videos', ['comp_chapter_id'], unique=False)
    op.create_index(op.f('ix_comp_student_videos_sub_chapter_id'), 'comp_student_videos', ['sub_chapter_id'], unique=False)
    op.create_table('comp_topics',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comp_chapter_id', sa.Integer(), nullable=True),
    sa.Column('sub_chapter_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comp_chapter_id'], ['comp_chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_chapter_id'], ['comp_sub_chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_topics_comp_chapter_id'), 'comp_topics', ['comp_chapter_id'], unique=False)
    op.create_index(op.f('ix_comp_topics_sub_chapter_id'), 'comp_topics', ['sub_chapter_id'], unique=False)
    op.create_table('comp_chapter_activities',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('activity_group_id', sa.Integer(), nullable=False),
    sa.Column('comp_chapter_id', sa.Integer(), nullable=True),
    sa.Column('sub_chapter_id', sa.Integer(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('options', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('correct_option_index', sa.Integer(), nullable=True),
    sa.Column('answer_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('answer_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('answer_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_group_id'], ['comp_activity_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comp_chapter_id'], ['comp_chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_chapter_id'], ['comp_sub_chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_chapter_activities_activity_group_id'), 'comp_chapter_activities', ['activity_group_id'], unique=False)
    op.create_index(op.f('ix_comp_chapter_activities_comp_chapter_id'), 'comp_chapter_activities', ['comp_chapter_id'], unique=False)
    op.create_index(op.f('ix_comp_chapter_activities_sub_chapter_id'), 'comp_chapter_activities', ['sub_chapter_id'], unique=False)
    op.create_index(op.f('ix_activity_groups_chapter_id'), 'activity_groups', ['chapter_id'], unique=False)
    op.alter_column('activity_play_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_activity_play_sessions_chapter_id'), 'activity_play_sessions', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_additional_notes_chapter_id'), 'additional_notes', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_boards_class_level_id'), 'boards', ['class_level_id'], unique=False)
    op.create_index(op.f('ix_chapter_activities_activity_group_id'), 'chapter_activities', ['activity_group_id'], unique=False)
    op.create_index(op.f('ix_chapter_activities_chapter_id'), 'chapter_activities', ['chapter_id'], unique=False)
    op.alter_column('chapter_artifacts', 'content',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('chapter_artifacts', 'error',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.create_index(op.f('ix_chapters_subject_id'), 'chapters', ['subject_id'], unique=False)
    op.create_index(op.f('ix_llm_images_chapter_id'), 'llm_images', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_llm_notes_chapter_id'), 'llm_notes', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_llm_textbooks_chapter_id'), 'llm_textbooks', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_mediums_board_id'), 'mediums', ['board_id'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_previous_year_question_papers_subject_id'), 'previous_year_question_papers', ['subject_id'], unique=False)
    op.create_index(op.f('ix_qa_patterns_chapter_id'), 'qa_patterns', ['chapter_id'], unique=False)
    op.alter_column('razorpay_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('razorpay_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('razorpay_orders_razorpay_order_id_key'), 'razorpay_orders', type_='unique')
    op.drop_index(op.f('ix_razorpay_orders_razorpay_order_id'), table_name='razorpay_orders')
    op.create_index(op.f('ix_razorpay_orders_razorpay_order_id'), 'razorpay_orders', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_student_notes_chapter_id'), 'student_notes', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_student_textbooks_chapter_id'), 'student_textbooks', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_student_videos_chapter_id'), 'student_videos', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_subjects_medium_id'), 'subjects', ['medium_id'], unique=False)
    op.create_index(op.f('ix_topics_chapter_id'), 'topics', ['chapter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_chapter_id'), table_name='topics')
    op.drop_index(op.f('ix_subjects_medium_id'), table_name='subjects')
    op.drop_index(op.f('ix_student_videos_chapter_id'), table_name='student_videos')
    op.drop_index(op.f('ix_student_textbooks_chapter_id'), table_name='student_textbooks')
    op.drop_index(op.f('ix_student_notes_chapter_id'), table_name='student_notes')
    op.drop_index(op.f('ix_razorpay_orders_razorpay_order_id'), table_name='razorpay_orders')
    op.create_index(op.f('ix_razorpay_orders_razorpay_order_id'), 'razorpay_orders', ['razorpay_order_id'], unique=False)
    op.create_unique_constraint(op.f('razorpay_orders_razorpay_order_id_key'), 'razorpay_orders', ['razorpay_order_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('razorpay_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('razorpay_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_qa_patterns_chapter_id'), table_name='qa_patterns')
    op.drop_index(op.f('ix_previous_year_question_papers_subject_id'), table_name='previous_year_question_papers')
    op.alter_column('notifications', 'sent_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_mediums_board_id'), table_name='mediums')
    op.drop_index(op.f('ix_llm_textbooks_chapter_id'), table_name='llm_textbooks')
    op.drop_index(op.f('ix_llm_notes_chapter_id'), table_name='llm_notes')
    op.drop_index(op.f('ix_llm_images_chapter_id'), table_name='llm_images')
    op.drop_index(op.f('ix_chapters_subject_id'), table_name='chapters')
    op.alter_column('chapter_artifacts', 'error',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('chapter_artifacts', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_chapter_activities_chapter_id'), table_name='chapter_activities')
    op.drop_index(op.f('ix_chapter_activities_activity_group_id'), table_name='chapter_activities')
    op.drop_index(op.f('ix_boards_class_level_id'), table_name='boards')
    op.drop_index(op.f('ix_additional_notes_chapter_id'), table_name='additional_notes')
    op.drop_index(op.f('ix_activity_play_sessions_chapter_id'), table_name='activity_play_sessions')
    op.alter_column('activity_play_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_activity_groups_chapter_id'), table_name='activity_groups')
    op.drop_index(op.f('ix_comp_chapter_activities_sub_chapter_id'), table_name='comp_chapter_activities')
    op.drop_index(op.f('ix_comp_chapter_activities_comp_chapter_id'), table_name='comp_chapter_activities')
    op.drop_index(op.f('ix_comp_chapter_activities_activity_group_id'), table_name='comp_chapter_activities')
    op.drop_table('comp_chapter_activities')
    op.drop_index(op.f('ix_comp_topics_sub_chapter_id'), table_name='comp_topics')
    op.drop_index(op.f('ix_comp_topics_comp_chapter_id'), table_name='comp_topics')
    op.drop_table('comp_topics')
    op.drop_index(op.f('ix_comp_student_videos_sub_chapter_id'), table_name='comp_student_videos')
    op.drop_index(op.f('ix_comp_student_videos_comp_chapter_id'), table_name='comp_student_videos')
    op.drop_table('comp_student_videos')
    op.drop_index(op.f('ix_comp_student_textbooks_sub_chapter_id'), table_name='comp_student_textbooks')
    op.drop_index(op.f('ix_comp_student_textbooks_comp_chapter_id'), table_name='comp_student_textbooks')
    op.drop_table('comp_student_textbooks')
    op.drop_index(op.f('ix_comp_student_notes_sub_chapter_id'), table_name='comp_student_notes')
    op.drop_index(op.f('ix_comp_student_notes_comp_chapter_id'), table_name='comp_student_notes')
    op.drop_table('comp_student_notes')
    op.drop_index(op.f('ix_comp_qa_patterns_sub_chapter_id'), table_name='comp_qa_patterns')
    op.drop_index(op.f('ix_comp_qa_patterns_comp_chapter_id'), table_name='comp_qa_patterns')
    op.drop_table('comp_qa_patterns')
    op.drop_index(op.f('ix_comp_llm_textbooks_sub_chapter_id'), table_name='comp_llm_textbooks')
    op.drop_index(op.f('ix_comp_llm_textbooks_comp_chapter_id'), table_name='comp_llm_textbooks')
    op.drop_table('comp_llm_textbooks')
    op.drop_index(op.f('ix_comp_llm_notes_sub_chapter_id'), table_name='comp_llm_notes')
    op.drop_index(op.f('ix_comp_llm_notes_comp_chapter_id'), table_name='comp_llm_notes')
    op.drop_table('comp_llm_notes')
    op.drop_index(op.f('ix_comp_llm_images_sub_chapter_id'), table_name='comp_llm_images')
    op.drop_index(op.f('ix_comp_llm_images_comp_chapter_id'), table_name='comp_llm_images')
    op.drop_table('comp_llm_images')
    op.drop_index(op.f('ix_comp_chapter_artifacts_sub_chapter_id'), table_name='comp_chapter_artifacts')
    op.drop_index(op.f('ix_comp_chapter_artifacts_comp_chapter_id'), table_name='comp_chapter_artifacts')
    op.drop_index(op.f('ix_comp_chapter_artifacts_artifact_type'), table_name='comp_chapter_artifacts')
    op.drop_table('comp_chapter_artifacts')
    op.drop_index(op.f('ix_comp_additional_notes_sub_chapter_id'), table_name='comp_additional_notes')
    op.drop_index(op.f('ix_comp_additional_notes_comp_chapter_id'), table_name='comp_additional_notes')
    op.drop_table('comp_additional_notes')
    op.drop_index(op.f('ix_comp_activity_groups_sub_chapter_id'), table_name='comp_activity_groups')
    op.drop_index(op.f('ix_comp_activity_groups_comp_chapter_id'), table_name='comp_activity_groups')
    op.drop_table('comp_activity_groups')
    op.drop_index(op.f('ix_comp_sub_chapters_chapter_id'), table_name='comp_sub_chapters')
    op.drop_table('comp_sub_chapters')
    op.drop_index(op.f('ix_mock_test_questions_mock_test_id'), table_name='mock_test_questions')
    op.drop_table('mock_test_questions')
    op.drop_index(op.f('ix_comp_chapters_subject_id'), table_name='comp_chapters')
    op.drop_table('comp_chapters')
    op.drop_index(op.f('ix_mock_tests_level_id'), table_name='mock_tests')
    op.drop_table('mock_tests')
    op.drop_index(op.f('ix_comp_subjects_level_id'), table_name='comp_subjects')
    op.drop_table('comp_subjects')
    op.drop_index(op.f('ix_comp_previous_year_papers_level_id'), table_name='comp_previous_year_papers')
    op.drop_table('comp_previous_year_papers')
    op.drop_index(op.f('ix_comp_levels_medium_id'), table_name='comp_levels')
    op.drop_table('comp_levels')
    op.drop_index(op.f('ix_comp_exam_mediums_exam_id'), table_name='comp_exam_mediums')
    op.drop_table('comp_exam_mediums')
    op.drop_index(op.f('ix_exams_exam_category_id'), table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_exam_categories_name'), table_name='exam_categories')
    op.drop_table('exam_categories')
    # ### end Alembic commands ###
