"""add chapter_artifacts table

Revision ID: c9e0a304ea23
Revises: 02dc3f7cd960
Create Date: 2026-02-15 18:20:42.463261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e0a304ea23'
down_revision: Union[str, Sequence[str], None] = '02dc3f7cd960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter_artifacts',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_artifacts_artifact_type'), 'chapter_artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_chapter_artifacts_chapter_id'), 'chapter_artifacts', ['chapter_id'], unique=False)
    op.drop_constraint(op.f('topics_chapter_id_fkey'), 'topics', type_='foreignkey')
    op.create_foreign_key(None, 'topics', 'chapters', ['chapter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.create_foreign_key(op.f('topics_chapter_id_fkey'), 'topics', 'chapters', ['chapter_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chapter_artifacts_chapter_id'), table_name='chapter_artifacts')
    op.drop_index(op.f('ix_chapter_artifacts_artifact_type'), table_name='chapter_artifacts')
    op.drop_table('chapter_artifacts')
    # ### end Alembic commands ###
