"""add_comp_chapter_faqs

Revision ID: f37f4f255924
Revises: 3852c215bdf6
Create Date: 2026-06-26 00:12:39.091527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37f4f255924'
down_revision: Union[str, Sequence[str], None] = '3852c215bdf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comp_chapter_faqs',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('comp_chapter_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comp_chapter_id'], ['comp_chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_chapter_faqs_comp_chapter_id'), 'comp_chapter_faqs', ['comp_chapter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comp_chapter_faqs_comp_chapter_id'), table_name='comp_chapter_faqs')
    op.drop_table('comp_chapter_faqs')
    # ### end Alembic commands ###
